name: "Notify Teams"

inputs:
  run_id:
    description: "Current run id"
    required: true
  hook_url:
    description: "URL of MS Teams hook"
    required: true

runs:
  using: "composite"
  steps:
    - name: execute
      shell: bash
      run: |
        RUN_INFO=$(curl https://api.github.com/repos/${{ github.repository }}/actions/runs/${{ inputs.run_id }}) \
        COMMIT_MSG=$(echo $RUN_INFO | jq -r .head_commit.message) \
        echo "TEST_MESSAGE" \
        echo $COMMIT_MSG \
        WEBPAGE_URL=$(echo $RUN_INFO | jq -r .html_url) \
        echo $WEBPAGE_URL \
        curl -X POST \
        --url ${{ inputs.hook_url }} \
        --header 'authorization: Bearer ${{ secrets.GITHUB_TOKEN }}' \
        --header "Content-Type: application/json; charset=utf-8" \
        --data '{
        "@context": "https://schema.org/extensions",
        "@type": "MessageCard",
        "text": "Run failed",
        "sections": [
            {
                "facts": [
                    {
                        "name": "Repository",
                        "value": "${{ github.repository }}"
                    },
                    {
                        "name": "Workflow",
                        "value": "${{ github.workflow }}"
                    },
                    {
                        "name": "Commit message",
                        "value": "'"$COMMIT_MSG"'"
                    }
                ]
            }
        ],
        "potentialAction": [
            {
                "@type": "OpenUri",
                "name": "View in GitHub",
                "targets": [
                    {
                        "os": "default",
                        "uri": "'"$WEBPAGE_URL"'"
                    }
                ]
            }
        ]
        }'
