name: "Notify Teams"

inputs:
  repository:
    description: "Repository full name in `organization/repo-name` format"
    required: true
  workflow_name:
    description: "Workflow name"
    required: true
  commit_sha:
    description: "Head commit SHA"
    required: true
  run_id:
    description: "Current run id"
    required: true
  hook_url:
    description: "URL of MS Teams hook"
    required: true

runs:
  using: "composite"
  steps:
    - name: execute
      shell: bash
      run: |
      curl -0 -v -X POST ${{inputs.hook_url}} -H "Content-Type: application/json; charset=utf-8" --data-binary @- << EOF
{
    "@context": "https://schema.org/extensions",
    "@type": "MessageCard",
    "text": "Run failed",
    "sections": [
        {
            "facts": [
                {
                    "name": "Repository",
                    "value": "${{inputs.repository}}"
                },
                {
                    "name": "Workflow",
                    "value": "${{inputs.workflow_name}}"
                },
                {
                    "name": "Commit message",
                    "value": "${{inputs.commit_msg}}"
                }
            ]
        }
    ],
    "potentialAction": [
        {
            "@type": "OpenUri",
            "name": "View in GitHub",
            "targets": [
                {
                    "os": "default",
                    "uri": "https://github.com/${{inputs.repository}}/runs/${{inputs.run_id}}"
                }
            ]
        }
    ]
}
EOF
