name: test

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build
    timeout-minutes: 30
    
    steps:
    - name: Get sources
      uses: actions/checkout@v2   
    
    - name: Install packages
      run: |
        npm install --no-audit --no-fund    

    - name: Build devextreme repo
      run: |
        cp -r ./node_modules/ ../node_modules/
        cp -r ../node_modules/ ./test_node_modules/

    - name: Copy build artifacts      
      uses: actions/upload-artifact@v2
      with:
        name: sources        
        path: test_node_modules/
        retention-days: 7
    
test:
    needs: build    

    runs-on: ubuntu-latest
    name: test
    timeout-minutes: 60

    steps:
    - name: Get sources
      uses: actions/checkout@v2        

    - name: Run npm install
      run: |
        npm install --no-package-lock --no-audit --no-fund

    - name: Download sources
      uses: actions/download-artifact@v2
      with:
        name: sources
        path: ../sources

    - name: Install devextreme package
      run: |        
        npm install --no-package-lock ../sources
  