name: Dispatched WF

on:
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest
    name: Generate Documentation

    steps:
        - name: Print Env
          run: echo ${{ github.ref_name }}
