name: test commit list

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build
    timeout-minutes: 30
    
    steps:
    
    - name: Install packages
      run: |
        $GITHUB_REF
        echo "$GITHUB_HEAD_REF"
        echo "$GITHUB_BASE_REF"
