name: test commit list

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build
    timeout-minutes: 30
    
    steps:

    - name: Get sources
      uses: actions/checkout@v2   
    
    - name: Install packages
      run: |
        git status
        echo git --no-pager diff --name-only FETCH_HEAD $(git merge-base FETCH_HEAD master)
        git --no-pager diff --name-only FETCH_HEAD $(git merge-base FETCH_HEAD master)
