name: test commit list

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build
    timeout-minutes: 30
    
    steps:

    - name: Get sources
      uses: actions/checkout@v2   
    
    - name: Install packages
      run: |
        git diff --name-status $GITHUB_HEAD_REF $GITHUB_BASE_REF
