name: test commit list

on:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build
    timeout-minutes: 30
    
    steps:

    - name: Get sources
      uses: actions/checkout@v2   
    
    - name: Install packages
      run: |
        curl -H "Accept: application/vnd.github.v3+json" https://api.github.com/repos/${{github.repository}}/pulls/${{github.event.pull_request.number}}/files > rawfilenames.json
        
#        git status
#        echo git --no-pager diff --name-only FETCH_HEAD $(git merge-base FETCH_HEAD master)
#        git --no-pager diff --name-only FETCH_HEAD $(git merge-base FETCH_HEAD master)
