name: Comments test

concurrency:
  group: wf-${{github.event.pull_request.number}}-${{github.workflow}}
  cancel-in-progress: true

on:
  pull_request:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build
    timeout-minutes: 30
    
    steps:

    - name: Check comments
      id: wait-for-test
      if: ${{ github.event.issue.pull_request && !contains(github.event.comment.body, '/force') }}
      run: echo "No comments!"
