name: Self-hosted

concurrency:
  group: wf-${{github.event.pull_request.number}}-${{github.workflow}}
  cancel-in-progress: true

on:
  workflow_dispatch:
  pull_request:
    types: [labeled, unlabeled, opened, synchronize, reopened]

jobs:
  build:
    runs-on: self-hosted
    name: Build
    timeout-minutes: 30
    
    steps:

    - name: checkout
      uses: actions/checkout@v2

    - name: install-packages
      run: npm i
