name: Self-hosted

concurrency:
  group: wf-${{github.event.pull_request.number}}-${{github.workflow}}
  cancel-in-progress: true

on:
  workflow_dispatch:
  pull_request:
    types: [labeled, unlabeled, opened, synchronize, reopened]

jobs:
  build:
    runs-on: self-hosted
    name: Build
    timeout-minutes: 30
    
    steps:

    - name: checkout
      uses: actions/checkout@v2

    - name: install-packages
      run: npm i

    - name: Restore npm cache
      uses: actions/cache@v2
      with:
        path: ./node_modules
        key: ${{ runner.os }}-node-modules-${{ hashFiles('**/package.json') }}
        restore-keys: ${{ runner.os }}-node-modules

    - name: Zip artifacts 
      run: |
        7z a -tzip -mx3 -mmt2 artifacts.zip node_modules

    - name: Upload build artifacts
      uses: actions/upload-artifact@v2
      with:
        name: devextreme-artifacts
        path: artifacts.zip
        retention-days: 1
