name: Comments test

concurrency:
  group: wf-${{github.event.pull_request.number}}-${{github.workflow}}
  cancel-in-progress: true

on:
  pull_request:
    types: [labeled, unlabeled, opened, synchronize, reopened]

jobs:
  build:
    runs-on: self-hosted
    name: Build
    timeout-minutes: 30
    
    steps:

    - name: Check comments
      id: wait-for-test
      if: ${{ github.event_name == 'pull_request' && !contains(github.event.pull_request.labels.*.name, 'force visual tests') }}
      run: echo Hello!

    # - uses: actions/upload-artifact@v2
    #   with:
    #     name: my-artifact
    #     path: log.txt
