name: test commit list

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build
    timeout-minutes: 30
    
    steps:

    - name: Get sources
      uses: actions/checkout@v2   
    
    - name: Install packages
      run: exit 1

  notify:
    runs-on: ubuntu-latest
    name: Send notifications
    if: always()

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Execute
        uses: ./.github/actions/send-teams-notifiaction
        with:
          hook_url: ${{secrets.FAILURE_NOTIFICATION_URL}}
          repository: ${{github.repository}}
          workflow_name: ${{github.action}}
          commit_sha: ${{github.sha}}
          run_id: ${{github.run_id}}
