name: WF_LABELS

on:
  pull_request:

jobs:
  generate:
    runs-on: ubuntu-latest
    name: Generate Documentation

    steps:
        - name: Print Env
          run: |
            echo test
            echo ${{ github.event.pull_request.labels }}
